name:

on:
  push

jobs:
  run_Tests:
    runs-on: ubuntu-latest


    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup JDK
          uses: actions/setup-java@v1
          with:
            java-version: '19'

        - name: Update system
          run: |
            sudo apt-get update

        - name: Install Chrome
          run: |
            sudo apt-get -y install google-chrome-stable=113.0.5672.92-1

        - name: Build and test with Maven
          run: mvn clean test

        - name: Generate allure report
          uses: simple-elf/allure-report-action@master
          if: always()
          id: allure-report
          with:
            allure_results: allure-results
            gh_pages: gh-pages
            allure_report: allure-report
            allure_history: allure-history

        - name: Create a gh-pages branch containing allure report
          if: always()
          uses: peaceiris/actions-gh-pages@v2
          env:
            PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PUBLISH_BRANCH: gh-pages
            PUBLISH_DIR: allure-history



