name:

on:
  push

jobs:
  run_Tests:
    runs-on: ubuntu-latest


    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Setup JDK
          uses: actions/setup-java@v3
          with:
            java-version: '19'

        - name: Install Chrome and ChromeDriver
          run: |
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable

        - name: Build and test with Maven
          run: mvn clean test

        - name: Generate allure report
          uses: simple-elf/allure-report-action@master
          if: always()
          id: allure-report
          with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history



