name:

on:
  push

jobs:
  run_Tests:
    runs-on: ubuntu-latest


    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup JDK
          uses: actions/setup-java@v1
          with:
            java-version: '11'

        - name: Install Chrome and ChromeDriver
          run: |
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable

        - name: Build and test with Maven
          run: mvn test



